//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrviProjektniZadatakHCI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrviProjektniZadatakHCI.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet.
        /// </summary>
        public static string _1Subject {
            get {
                return ResourceManager.GetString("1Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta.
        /// </summary>
        public static string _CourseNameText {
            get {
                return ResourceManager.GetString(" CourseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisutan/Odsutan.
        /// </summary>
        public static string Absent_Present {
            get {
                return ResourceManager.GetString("Absent/Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademsko zvanje.
        /// </summary>
        public static string AcademicTitleText {
            get {
                return ResourceManager.GetString("AcademicTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbor entiteta za unos.
        /// </summary>
        public static string AddingEntity {
            get {
                return ResourceManager.GetString("AddingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Profesora.
        /// </summary>
        public static string AddProfessor {
            get {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je zadužio kurs.
        /// </summary>
        public static string AssignMessage {
            get {
                return ResourceManager.GetString("AssignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodijeli kurs.
        /// </summary>
        public static string AssignText {
            get {
                return ResourceManager.GetString("AssignText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled Prisustva.
        /// </summary>
        public static string AttendanceO {
            get {
                return ResourceManager.GetString("AttendanceO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vođenje evidencije o prisustvu.
        /// </summary>
        public static string AttendanceRecordMText {
            get {
                return ResourceManager.GetString("AttendanceRecordMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled Prisustva.
        /// </summary>
        public static string AttendanceReviewText {
            get {
                return ResourceManager.GetString("AttendanceReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo.
        /// </summary>
        public static string AttendanceText {
            get {
                return ResourceManager.GetString("AttendanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plava tema.
        /// </summary>
        public static string BlueText {
            get {
                return ResourceManager.GetString("BlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra.
        /// </summary>
        public static string CodeText {
            get {
                return ResourceManager.GetString("CodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista predmeta.
        /// </summary>
        public static string CourseList {
            get {
                return ResourceManager.GetString("CourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DateTimeText {
            get {
                return ResourceManager.GetString("DateTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        public static string DeadLineText {
            get {
                return ResourceManager.GetString("DeadLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECTS.
        /// </summary>
        public static string ECTSText {
            get {
                return ResourceManager.GetString("ECTSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime predmeta.
        /// </summary>
        public static string EnterCourseName {
            get {
                return ResourceManager.GetString("EnterCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite korisnika kojeg unosite.
        /// </summary>
        public static string EnteringUser {
            get {
                return ResourceManager.GetString("EnteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Ispita.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ispita.
        /// </summary>
        public static string ExamDateText {
            get {
                return ResourceManager.GetString("ExamDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra zadatka.
        /// </summary>
        public static string ExamIdText {
            get {
                return ResourceManager.GetString("ExamIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiti.
        /// </summary>
        public static string ExamManagement {
            get {
                return ResourceManager.GetString("ExamManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiti po predmetima.
        /// </summary>
        public static string ExamsByCourses {
            get {
                return ResourceManager.GetString("ExamsByCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispit.
        /// </summary>
        public static string ExamText {
            get {
                return ResourceManager.GetString("ExamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ocjena.
        /// </summary>
        public static string GradeEntry {
            get {
                return ResourceManager.GetString("GradeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ocjena.
        /// </summary>
        public static string GradeEntryText {
            get {
                return ResourceManager.GetString("GradeEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled ocjena.
        /// </summary>
        public static string GradeReview {
            get {
                return ResourceManager.GetString("GradeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjena.
        /// </summary>
        public static string GradeText {
            get {
                return ResourceManager.GetString("GradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelena tema.
        /// </summary>
        public static string GreenText {
            get {
                return ResourceManager.GetString("GreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaci i Ispiti.
        /// </summary>
        public static string HomeworkExamText {
            get {
                return ResourceManager.GetString("HomeworkExamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaći zadaci.
        /// </summary>
        public static string Homeworks {
            get {
                return ResourceManager.GetString("Homeworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaći zadatak.
        /// </summary>
        public static string HomeworkText {
            get {
                return ResourceManager.GetString("HomeworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator.
        /// </summary>
        public static string IdText {
            get {
                return ResourceManager.GetString("IdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj indeksa.
        /// </summary>
        public static string IndexNumberText {
            get {
                return ResourceManager.GetString("IndexNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum predavanja.
        /// </summary>
        public static string LectureD {
            get {
                return ResourceManager.GetString("LectureD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljenje dodjelama.
        /// </summary>
        public static string ManageAssignmentText {
            get {
                return ResourceManager.GetString("ManageAssignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje predmetima i aktivnostima.
        /// </summary>
        public static string ManagementSA {
            get {
                return ResourceManager.GetString("ManagementSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj bodova.
        /// </summary>
        public static string MaximumPointsText {
            get {
                return ResourceManager.GetString("MaximumPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled prisustva po predmetima.
        /// </summary>
        public static string OAbyCourses {
            get {
                return ResourceManager.GetString("OAbyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled aktivnosti i rezultata.
        /// </summary>
        public static string OverviewAR {
            get {
                return ResourceManager.GetString("OverviewAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postignuća po kursevima.
        /// </summary>
        public static string PerformanceByCourses {
            get {
                return ResourceManager.GetString("PerformanceByCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodovi.
        /// </summary>
        public static string PointsText {
            get {
                return ResourceManager.GetString("PointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisutan.
        /// </summary>
        public static string PresentText {
            get {
                return ResourceManager.GetString("PresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        public static string ProfessorText {
            get {
                return ResourceManager.GetString("ProfessorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos prisustva.
        /// </summary>
        public static string RecordAttendance {
            get {
                return ResourceManager.GetString("RecordAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crvena tema.
        /// </summary>
        public static string RedText {
            get {
                return ResourceManager.GetString("RedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj prisustvo.
        /// </summary>
        public static string SaveAttendanceButton {
            get {
                return ResourceManager.GetString("SaveAttendanceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        public static string StudentAchievement {
            get {
                return ResourceManager.GetString("StudentAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string StudentList {
            get {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentText {
            get {
                return ResourceManager.GetString("StudentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        public static string SubjectText {
            get {
                return ResourceManager.GetString("SubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string SurnameText {
            get {
                return ResourceManager.GetString("SurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavljanje sistema.
        /// </summary>
        public static string SystemSetup {
            get {
                return ResourceManager.GetString("SystemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje zadataka.
        /// </summary>
        public static string TaskAddText {
            get {
                return ResourceManager.GetString("TaskAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv zadatka.
        /// </summary>
        public static string TaskNameText {
            get {
                return ResourceManager.GetString("TaskNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled zadataka.
        /// </summary>
        public static string TaskOverviewText {
            get {
                return ResourceManager.GetString("TaskOverviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Zadatka.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razduži .
        /// </summary>
        public static string UnassignCourse {
            get {
                return ResourceManager.GetString("UnassignCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor je razdužen sa fakulteta.
        /// </summary>
        public static string UnassignMessage {
            get {
                return ResourceManager.GetString("UnassignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi entitet za  ažuriranje.
        /// </summary>
        public static string UpdateEntity {
            get {
                return ResourceManager.GetString("UpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina studija.
        /// </summary>
        public static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
    }
}
